/*
-- Query: SELECT * FROM GAME
LIMIT 0, 1000

-- Date: 2017-11-16 18:03
*/
INSERT INTO `GAME` (`Game_ID`,`Title`,`ESRB_Rtng`,`Company_ID`,`Description`) VALUES ('des','Destiny','T','act','You are one of humanity’s last remaining Guardians. Your home and your power has been taken from you by a brutal invader – Ghaul. With humanity on the brink, it’s up to you to fight back and reclaim our world.');
INSERT INTO `GAME` (`Game_ID`,`Title`,`ESRB_Rtng`,`Company_ID`,`Description`) VALUES ('des2','Destiny 2','T','act','Humanity’s last safe city has fallen to an overwhelming invasion force, led by Ghaul, the imposing commander of the brutal Red Legion. He has stripped the city’s Guardians of their power, and forced the survivors to flee. You will venture to mysterious, unexplored worlds of our solar system to discover an arsenal of weapons and devastating new combat abilities.');
INSERT INTO `GAME` (`Game_ID`,`Title`,`ESRB_Rtng`,`Company_ID`,`Description`) VALUES ('ffvii','Final Fantasy VII','T','se','Mako: the discovery of this natural resource drawn directly from the planet\'s life force marked the dawn of a new era, and now the energy sustains the lives of people across the world. However, the Shinra Company has monopolized mako production, and in doing so established a powerful hegemony, its influence reaching the far corners of the globe. Cloud, a former member of Shinra\'s military organization, SOLDIER, joins the anti-Shinra resistance group AVALANCHE, despite caring little for their motives. During one of the groups attempts to stop the company, they learn of the return of Sephiroth, Clouds nemesis, and that with his reemergence, the planet is in greater danger than anyone had expected. With the fate of the world riding on their success, Cloud and his allies set out to quell this deadly threat.');
INSERT INTO `GAME` (`Game_ID`,`Title`,`ESRB_Rtng`,`Company_ID`,`Description`) VALUES ('pkmsm','Pokemon: Sun and Moon','E','gf','The player and the mother move from Kanto to Alola. However, at roughly the same time, a young girl is seen escaping what seems to be a lab with an unidentified Pokémon in her bag. As she gets cornered by the workers in the area, the Pokémon teleports itself and the girl away from the lab and away from danger.');
INSERT INTO `GAME` (`Game_ID`,`Title`,`ESRB_Rtng`,`Company_ID`,`Description`) VALUES ('pkmu2sm','Pokemon:Ultra Sun and Moon','E','gf','tbd');
INSERT INTO `GAME` (`Game_ID`,`Title`,`ESRB_Rtng`,`Company_ID`,`Description`) VALUES ('StarC','StarCraft','T','bl','Long ago four supercarriers loaded with political dissidents and convicts from Earth crash-landed on the distant planets of Tarsonis, Moria, and Umoja.');
